# Generated by Django 6.0.6 on 2026-07-08 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(unique=True, verbose_name='Serial No')),
                ('mobile_name', models.CharField(max_length=100, verbose_name='Mobile Name')),
                ('imei_no', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='IMEI must be exactly 15 digits.', regex='^\\d{15}$')], verbose_name='IMEI/SKU')),
                ('actual_price', models.PositiveIntegerField(verbose_name='Actual Price')),
                ('sold_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sold Price')),
                ('sold_date', models.DateField(blank=True, null=True, verbose_name='Sale Date')),
                ('remarks', models.TextField(blank=True, max_length=200, null=True, verbose_name='Remarks')),
                ('remarks_read', models.BooleanField(default=False, verbose_name='Read Status')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By')),
            ],
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
