# Generated by Django 6.0.6 on 2026-07-12 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mobileinventory_delete_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('is_regular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('paid_by', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='mobileinventory',
            name='sold_date',
        ),
        migrations.AlterField(
            model_name='mobileinventory',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mobileinventory',
            name='imei_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mobileinventory',
            name='mobile_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mobileinventory',
            name='remarks',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobileinventory',
            name='remarks_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mobileinventory',
            name='serial_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='mobileinventory',
            name='sold_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobileinventory',
            name='updated_by',
            field=models.CharField(blank=True, default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partial', 'Partial')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
            ],
        ),
    ]
