# Generated by Django 6.0.6 on 2026-07-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_expense_remove_mobileinventory_sold_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='due_date',
            new_name='shipment_date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='sales',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Credit', 'Udhaar')], default='Cash', max_length=50),
        ),
        migrations.AddField(
            model_name='sales',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, default='2026-07-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobileinventory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobileinventory',
            name='sold_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mobileinventory',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
