# Generated by Django 6.0.6 on 2026-07-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_due_date_sales_shipment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mobileinventory', verbose_name='Select Mobile (IMEI)'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Credit', 'Loan')], default='Cash', max_length=50),
        ),
    ]
